# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

#### Import NumPy (as np)

In [2]:
import numpy as np

#### Set the seed to 0

In [3]:
np.random.seed(0)

#### Create an array of 10 zeros 

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [7]:
np.full(10, 5.0)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50 (in order)

In [9]:
np.arange(10,51,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [10]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 5x5 matrix with values ranging from 0 to 8

In [15]:
np.random.randint(0,9,25).reshape(5,5)

array([[5, 0, 3, 3, 7],
       [3, 5, 2, 4, 7],
       [6, 8, 8, 1, 6],
       [7, 7, 8, 1, 5],
       [8, 4, 3, 0, 3]])

#### Create a 3x3 identity matrix

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [17]:
np.random.random(1)

array([0.95715516])

#### Use NumPy to generate a 5x5 matrix of 25 random numbers sampled from a standard normal distribution

In [18]:
np.random.normal(0,1,25).reshape(5,5)

array([[ 1.41437719, -0.12405066,  2.00815709,  0.22988654,  0.60489373],
       [ 1.62715982,  1.59456053,  0.23043417, -0.06491034, -0.96898025],
       [ 0.59124281, -0.7827755 , -0.44423283, -0.34518616, -0.88180055],
       [-0.44265324, -0.5409163 , -1.32322737, -0.11279892,  0.90734594],
       [ 0.81526991,  0.22909795, -1.02617878,  0.47752547,  1.29269823]])

#### Create the following matrix (hint: use `linspace` with `reshape`):

Expected result:
```python
array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])
```

In [23]:
np.linspace(0, 1, 100).reshape(10,10)

array([[0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
        0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909],
       [0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
        0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919],
       [0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
        0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929],
       [0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
        0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939],
       [0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
        0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949],
       [0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
        0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ],
       [0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
        0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ],
       [0.70707071, 0.71717172, 0.7272727

#### Create an array of 20 linearly spaced points between 0 and 1:

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [38]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
np.array([12,13,14,15,17,18,19,20,22,23,24,25]).reshape(3,4)

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

```python 
[Output]:
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```

In [26]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
20

20

```python 
[Output]:
20
```

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
np.arange(2,13,5).reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

```python 
[Output]:
array([[ 2],
       [ 7],
       [12]])

```

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
np.arange(21,26)

array([21, 22, 23, 24, 25])

```python 
[Output]:
array([21, 22, 23, 24, 25])

```

In [33]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
np.arange(16,26).reshape(2,5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

```python 
[Output]:
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

### Conditional Indexing (AKA fancy indexing)

In [48]:
import numpy as np
np.random.seed(0)

In [49]:
mat = np.random.randint(-5, 50, size=[5,5])
mat

array([[39, 42, 48, -5, -2],
       [-2, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7, -4, 33, 34],
       [18, 41, 19, 12, 32]])

#### Select all elements that are greater than 5.

In [39]:
mat[mat > 5]

array([39, 42, 48, 34, 14, 16, 45, 31, 18, 19, 19,  7, 33, 34, 18, 41, 19,
       12, 32])

Expected result:
```python
array([39, 42, 48, 34, 14, 16, 45, 31, 18, 19, 19,  7, 33, 34, 18, 41, 19,
       12, 32])
```

#### Select all rows where the first element is less than or equal to 20.

In [43]:
mat[mat[:, 0] <= 20]

array([[-2, 34,  4, 14, 16],
       [19,  7, -4, 33, 34],
       [18, 41, 19, 12, 32]])

Expected result:
```python
array([[-2, 34,  4, 14, 16],
       [19,  7, -4, 33, 34],
       [18, 41, 19, 12, 32]])
```

### Replace all negative elements with 0.

In [50]:
tmp = mat
tmp[tmp < 0] = 0
tmp

array([[39, 42, 48,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])

Expected result:
```python
array([[39, 42, 48,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])
```

### Calculate the sum of all elements that are less than or equal to 5.

In [51]:
sum(mat[mat<=5])

5

Expected result: `5`

### Calculate the mean of all elements in the last column.

In [53]:
np.mean(mat[:,4])

20.2

Expected result: `20.2`

#### Count the number of elements that are not equal to 0.

In [55]:
np.count_nonzero(mat != 0)

21

Expected result: `21`

#### Replace all elements equal to the maximum value of the matrix with 0.

In [60]:
tmp = mat
maximum = np.max(tmp)
tmp[tmp == maximum] = 0
tmp

array([[39, 42,  0,  0,  0],
       [ 0, 34,  4, 14, 16],
       [ 0, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])

Expected result:
```python
array([[39, 42,  0,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])
```

### Math on rows and columns

#### Add 5 to a all mat elements

In [56]:
mat = mat + 5

#### Get the sum of all the values in mat

In [62]:
sum(sum(mat))

433

#### Get the standard deviation of the values in mat

In [63]:
np.std(mat)

14.485081981128031

#### Get the sum of all the columns in mat

In [74]:
np.sum(mat, axis = 0)

array([ 76, 155,  41,  60, 101])

#### Get the sum of all the rows in mat

In [73]:
np.sum(mat, axis = 1)

array([ 81,  68,  69,  93, 122])

# Great Job!